//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StaffTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffTable()
        {
            this.EmployeeLeavingTables = new HashSet<EmployeeLeavingTable>();
            this.EmployeeSalaryTables = new HashSet<EmployeeSalaryTable>();
            this.StaffAttendanceTables = new HashSet<StaffAttendanceTable>();
            this.TimeTblTables = new HashSet<TimeTblTable>();
        }
    
        public int StaffID { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage ="{0} Required Field!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public int DesignationID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public double BasicSalary { get; set; }
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Address { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Qualification { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public bool IsActive { get; set; }
        public string Gender { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string HomePhone { get; set; }
        public bool Doyouhaveanydisability { get; set; }
        public string Ifdisabilityyesthengiveusdetail { get; set; }
        public bool Areyoutakinganymedication { get; set; }
        public string Ifmedicationyesthengiveus { get; set; }
        public bool AnyCriminaloffcenceagainstyou { get; set; }
        public string Ifcriminaloffcenceyesthengiveusdetail { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }

        public virtual DesignationTable DesignationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeavingTable> EmployeeLeavingTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalaryTable> EmployeeSalaryTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAttendanceTable> StaffAttendanceTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTblTable> TimeTblTables { get; set; }
    }
}
