//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.AttendanceTables = new HashSet<AttendanceTable>();
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
            this.SchoolLeavingTables = new HashSet<SchoolLeavingTable>();
            this.StudentPromoteTables = new HashSet<StudentPromoteTable>();
            this.SubmissionFeeTables = new HashSet<SubmissionFeeTable>();
        }
    
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public int ProgrameID { get; set; }
        public int ClassID { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string FatherName { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Date only")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "{0} Required Field!")]
        public System.DateTime DateofBirth { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string CNIC { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string FNIC { get; set; }
        public string Photo { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Date only")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "{0} Required Field!")]
        public System.DateTime AdmissionDate { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string PreviousSchool { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public Nullable<double> PreviousPercentage { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Address { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string Religion { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string TribeorCaste { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string FathersGuardiansOccupationofProfession { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string FathersGuardiansPostalAddress { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string PhoneOffice { get; set; }
        [Required(ErrorMessage = "{0} Required Field!")]
        public string PhoneResident { get; set; }
        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceTable> AttendanceTables { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLeavingTable> SchoolLeavingTables { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPromoteTable> StudentPromoteTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionFeeTable> SubmissionFeeTables { get; set; }
    }
}
